
public class Exception {
	/*public static void main(String args[]) {

        try {

                    System.out.print("Hello" + " " + 5 / 0);

        }

        catch(ArithmeticException e) {

                    System.out.print("World");           

        }*/
	 public static void main(String args[]) {  

         System.out.println(myFunc());

}

 double myFunc() {

         return 10.0;

}

}

